# Run from report/. Makefile also supports environments without latexmk.
$pdf_mode = 5;
$xelatex = 'xelatex -interaction=nonstopmode -halt-on-error -file-line-error %O %S';
$out_dir = 'build/content';
$bibtex_use = 2;
